### ISSUE TITLE
Annual Land Cover Change product stored in awesome gee is not correct

### ISSUE THREAD

**Issue by ultralighthiker** [samapriya/awesome-gee-community-datasets#124]
I am referencing the LCMAP data available here: https://gee-community-catalog.org/projects/lcmap/

Go to the sample code on the website and view LCACHG and LCPRI.  They are identical!
Sample code: https://code.earthengine.google.com/?scriptPath=users/sat-io/awesome-gee-catalog-examples:regional-landuse-landcover/LCMAP

I think this link needs to be updated to point toward the actual LCACHG data, which should range in value from 0-87
var lcachg = ee.ImageCollection("projects/sat-io/open-datasets/LCMAP/LCACHG");

Thanks!

**Comment by samapriya** [comment]
Great catch I will update this as I work on also updating LCMAP to v1.3

**Comment by samapriya** [comment]
So for LCACHG it turns out because I was adding the latest year there were no pixels that have a value different than current year so I just need to add a year that is not the latest or the first year to get the additional values. For the xml metadata this seems obvious but is hidden in a way. Closing this issue for now since the visualization was not really a bug but the range was

```
Any pixel value that is not 1-8 actually is an indication that land cover change has occurred between the current year and the previous year. The prior year land cover class provides the first value and the current year land cover class provides the second value
```

**Comment by ultralighthiker** [comment]
Samapriya -- Great, thanks so much for looking into this! Much appreciated.
