### ISSUE TITLE
(HiHydroSoil v2.0 layers) Saturated Hydraulic Conductivity

### ISSUE THREAD

**Issue by ccalvocm** [samapriya/awesome-gee-community-datasets#140]
Dear all:

First of all, thank you for this amazing community datasets. 

Regarding Saturated Hydraulic Conductivity (ksat) from HiHydroSoil v2.0 layers dataset, its values range from 0 - 1500 cm/d, which is reasonable, however, when I got a sample of it, I got values of ksat ranging from 0 - 195393 cm/d, which seems pretty high. My intuition is that these values are scaled to thousands, i.e. my sample ranges from 0 - 195.39 cm/d, which would make sense. I just wanted to be sure, ¿are values of ksat scaled by *1000 in the dataset?.

Thank you in advance.
Kind regards

![ksat_example](https://github.com/google/earthengine-community/assets/52244870/e2dc77a1-05b3-4caf-a18d-7a4b4563d332)

**Comment by samapriya** [comment]
Thank you for the question if you read the dataset description it clearly states 

The data layers originally consisting of float data type were multiplied by a factor of 10,000 and subsequently converted to integer type. It is therefore required to translate the data to the proper units by multiplying with 0.0001.

This is not really an issue type but you can always open a GitHub discussion next time rather than a GitHub issue. Hope that helps
